version: "3.8"

services:
  mysql:
    restart: always
    image: mysql:8.0.27
    container_name: ${PROJECT_NAME}-mysql
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: [ mysqld, --default-authentication-plugin=mysql_native_password, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_monitor_enable=all, --max-connections=1001 ]
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/db:/var/lib/mysql

  phpmyadmin:
    restart: always
    profiles:
      - dev
    container_name: ${PROJECT_NAME}-phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 50M
      PMA_HOST: mysql